# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_invoice_constraint_chronology
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 16.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-03-05 17:34+0000\n"
"PO-Revision-Date: 2023-03-05 17:34+0000\n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: account_invoice_constraint_chronology
#: model:ir.model.fields,field_description:account_invoice_constraint_chronology.field_account_journal__check_chronology
msgid "Check Chronology"
msgstr "检查顺序"

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting draft invoice dated before {date_invoice}"
" exists, please validate it first."
msgstr "时间顺序冲突：存在日期在{date_invoice}之前的发票草稿，请确认。"

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting validated invoice dated after "
"{date_invoice} exists."
msgstr "时间顺序冲突：日期在{date_invoice} 之后的已验证发票存在冲突。"

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: An invoice with a higher number {highest_name} dated "
"before {date_invoice} exists."
msgstr "时间顺序冲突：存在日期早于{date_invoice}的编号更高 {highest_name}的发票。"
